SDL-0189 Added reset timeout for SubtleAlert RPC
LuxoftSDL/generic_hmi pull request #13
Opened 2021-07-21 23:30 UTC by LiliiaShlikhtLuxoft

Added reset timeout for SubtleAlert RPC

Task:
[Generic HMI] It's unable to reset timeout for SubtleAlert RPC

2021-07-22 09:25 UTC, YuriiYefimenko requested changes

2021-07-22 09:25 UTC, YuriiYefimenko commented on src/js/SubtleAlert.js
> +        let count = store.getState().ui[store.getState().activeApp].resetTimeout.resetTimeoutValue / 1000;
i would suggest you move `count` to `mapStateToProps` and read form prop here

2021-07-22 09:25 UTC, YuriiYefimenko commented on src/js/SubtleAlert.js
> +        if (store.getState().ui[store.getState().activeApp].alert.softButtons == undefined) {
please, use strict  equality

2021-08-16 11:54 UTC, LiliiaShlikhtLuxoft commented
Closed, because it does not match the current request for functionality.

2021-08-16 11:54 UTC, closed without merging