Fix SubtleAlert
LuxoftSDL/generic_hmi pull request #19
Opened 2021-07-28 13:34 UTC by YuriiYefimenko

### Summary
fixed SubtleAlert after click on it
 error: `Cannot read property 'alert' of undefined`

2021-07-28 13:43 UTC, ValeriiMalkov requested changes

2021-07-28 13:43 UTC, ValeriiMalkov commented on src/js/Alert.js
> +            this.setState({alertCounter: store.getState().ui[store.getState().activeApp].alert.duration/1000});
Could it be replaced with suggestion below?
```suggestion
            this.setState({alertCounter: activeApp.alert.duration/1000});
```

2021-07-30 14:20 UTC, LiliiaShlikhtLuxoft approved these changes

2021-08-02 08:24 UTC, ValeriiMalkov approved these changes

2021-08-02 08:29 UTC, merged